networks:
  app:
    external: true

services:
  thesis:
    image: "ml-webapp"
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.thesis.loadbalancer.server.port=5000"
      - "traefik.http.routers.thesis.entrypoints=websecure"
      - "traefik.http.routers.thesis.tls.certresolver=production"
      - "traefik.http.routers.thesis.rule=Host(`thesis.admondtamang.com.np`)"
