networks:
  app:
    external: true

services:
  fraud-simulator:
    image: "ml-webapp"
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=5000"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=production"
      - "traefik.http.routers.web.rule=Host(`thesis.admondtamang.com.np`)"
